apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ix39a03vz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-896bdbe91a.fyb6.p3.openshiftapps.com/rhtap/rhtap-qe:408b8c7687e8729808edc4aca215acf1dde3bce0@sha256:d5ce5f504fd533322997ea3889937137f3c84aa8ee3f5d65ec142ff66d50d778
          name: container-image
