apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ix39a03vz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ix39a03vz-go 
  name: ix39a03vz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ix39a03vz-go 
